import type { Metadata } from "next"
import { Roboto } from "next/font/google"
import { Toaster } from "@/components/ui/toaster"
import ChatBox from "@/components/ui-chatBox/chat-box"
import "./globals.css"

// thêm font
const roboto = Roboto({
  subsets: ["latin"],
  weight: ["100", "300", "400", "500", "700", "900"],
  style: ["normal", "italic"],
  variable: "--font-roboto",
  display: "swap",
})

export const metadata: Metadata = {
  title: "Zero Movies",
  description: "Generated by create next app",
  icons: [{ rel: "icon", type: "image/png", url: "/logo2.png" }],
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${roboto.variable} antialiased`}>
        {children}
        <ChatBox />
        <Toaster />
      </body>
    </html>
  )
}
